#include <stdio.h>
int main()
{
    int n=99,m,s[n],t,a,j,i,p;
    char c,d;
    printf("请输入数据:\n");
    for(i=0;i<n;i++)
    {
        scanf("%d",&s[i]);
        if(getchar()=='\n')
        break;
    }
    n=++i;
    printf("数据读取完毕 ,请选择您的排列方式(由大到小:1;由小到大:2)\n");
    scanf("%c",&c);
    if(c=='1')
    {
    printf("排序结果为:\n");
    for(i=0;i<n-1;i++)
    {
        for(j=i+1;j<n;j++)
        {
            if(s[i]<s[j])
            {
               t=s[i];
               s[i]=s[j];
               s[j]=t;
            }
        }
        printf("%d>",s[i]);
    }
    printf("%d\n",s[i]);
    }
    else if(c=='2')
{
    printf("排序结果为:\n");
    for(i=0;i<n-1;i++)
    {
        for(j=i+1;j<n;j++)
        {
            if(s[i]>s[j])
            {
               t=s[i];
               s[i]=s[j];
               s[j]=t;
            }
        }
        printf("%d<",s[i]);
    }
    printf("%d\n",s[i]);
    }
    tp:
    printf("若需要插入数字输入‘3’;若需要改变排序方式:(由大到小:1;由小到大:2);若要结束程序输入‘0’\n");
    getchar();
    scanf("%c",&d);
    if((d=='3')&&(c=='1'))
    {
        printf("请输入要插入的数:\n");
        scanf("%d",&a);
        p=0;
        m=n++;
        while(a<s[p])
            p++;
        while(m>p)
             {
            s[m]=s[m-1];
            m--;
             }
        s[p]=a;
        m=n;
        printf("排序结果为:\n");
        for(i=0;i<m-1;i++)
            printf("%d>",s[i]);
        printf("%d\n",s[i]);
    }
    else if((d=='3')&&(c=='2'))
    {
        printf("请输入要插入的数:\n");
        scanf("%d",&a);
        p=0;
        m=n++;
        while(a>s[p])
            p++;
        while(m>p)
             {
            s[m]=s[m-1];
            m--;
             }
        s[p]=a;
        m=n;
        printf("排序结果为:\n");
        for(i=0;i<m-1;i++)
            printf("%d<",s[i]);
        printf("%d\n",s[i]);
    }
    else if(d=='1')
         {
             c=1;
    printf("排序结果为:\n");
    for(i=0;i<n-1;i++)
    {
        for(j=i+1;j<n;j++)
        {
            if(s[i]<s[j])
            {
               t=s[i];
               s[i]=s[j];
               s[j]=t;
            }
        }
        printf("%d>",s[i]);
    }
    printf("%d\n",s[i]);
    }
    else if(d=='2')
    {
        c=2;
    printf("排序结果为:\n");
    for(i=0;i<n-1;i++)
    {
        for(j=i+1;j<n;j++)
        {
            if(s[i]>s[j])
            {
               t=s[i];
               s[i]=s[j];
               s[j]=t;
            }
        }
        printf("%d<",s[i]);
    }
    printf("%d\n",s[i]);
    }
    else
    {
        printf("感谢您使用此程序，祝您生活愉快！");
        return 0;
    }
    goto tp;
}
